[package]
name = "infochallenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noodles = { version = "0.34.0", features = ["vcf", "bcf"]}
rayon = "1.7.0"
itertools = "0.10.5"
peroxide = "0.32.1"